module.exports = [
  "kawa z mlekiem",
  "szpital psychiatryczny",
  "poradnik młodej mamy",
  "czarno na białym",
  "zupa ogórkowa",
  "sklep meblowy",
  "pizza pepperoni",
  "zegar kieszonkowy",
  "wpaść jak śliwka w kompot",
  "w gorącej wodzie kąpany",
  "droga mleczna",
  "jeśli wpadniesz między wrony, musisz krakać jak i one",
  "baba z wozu, koniom lżej",
  "syn marnotrawny",
  "armia terakotowa",
  "wielki mur chiński",
  "szopka bożonarodzeniowa",
  "pytanie retoryczne",
  "uniwersytet medyczny",
  "lekarz rodzinny",
  "wysoki jak brzoza a głupi jak koza",
  "chleb powszedni",
  "balon z helem",
  "woda z sokiem",
  "strajk głodowy",
  "koń na biegunach",
  "mróz na szybie",
  "koło fortuny",
  "rosyjska ruletka",
  "ranny ptaszek",
  "ptaszek w klatce",
  "dzieci i ryby głosu nie mają",
  "skrzydła anielskie",
  "dziurawe wiadro",
  "serce z kamienia",
  "dziewczynka z zapałkami",
  "dziadek do orzechów",
];
